#!/usr/bin/env python
"""
A prototype for the ricopili bioinformatics pipeline. Uses MAGMA as an
example tool.
"""

import argparse as arg
import os

from bioinformatics.tools.region_annotator.region_annotator import RegionAnnotator
from bioinformatics.tools.magma.magma import Magma


def __main__():

    # Argument parser for umbrella program
    parser = arg.ArgumentParser()
    parser.add_argument("--mode", action="store", dest="mode",
                        choices=["drmaa", "qsub", "local"])
    parser.add_argument("--cluster-env", action="store", dest="cluster_env",
                        choices=["broad", "lisa", None])
    parser.add_argument("--output-dir", action="store", dest="output_dir")

    # breakout parsers for different tool pipelines
    subparsers = parser.add_subparsers(help="Tool sub-pipeline help.",
                                       dest="workflow")

    # Add tools to the workflow
    magma = Magma(subparsers)
    region_annotator = RegionAnnotator(subparsers)

    args = parser.parse_args()

    config = dict(vars(args))

    if args.workflow == "magma":
        magma.execute(execution_mode=args.mode,
                      context=args.cluster_env,
                      config=config)
    elif args.workflow == "region_annotator":
        region_annotator.execute(execution_mode=args.mode,
                                 context=args.cluster_env,
                                 config=config)


if __name__ == "__main__":
    __main__()
