daner: /home/unix/vassily/projects/pgc/ricopili_extension/ricopili_bioinformatics/test/resources/pgc_scz_chr22_subset.daner
output_dir: /home/unix/vassily/projects/pgc/ricopili_extension/ricopili_bioinformatics/test/data/
magma_bin: /home/unix/vassily/projects/pgc/ricopili_extension/ricopili_bioinformatics/resources/magma_linux/magma
ref_gene_loc: /home/unix/vassily/projects/pgc/ricopili_extension/ricopili_bioinformatics/resources/magma_macOS/reference_data/NCBI37.3.gene.loc
ref_1000g: /psych/ripke/share/vasa/magma_ref/g1000_eur
study_sample_size: 20000
